### ISSUE TITLE
How to generate demo site ?

### ISSUE THREAD

**Issue by guimard** [marcodpt/vue-tree-nav#1]
Hi,

I didn't succeed to generate demo from src. Could you help me here ?

Cheers,
Xavier

**Comment by marcodpt** [comment]
Hi,
I think it is like... you clone the repo on you machine then run (do you saw **package.json**?):
`npm install`
`npm run build` (this may be skiped)
`npm run start`
then if everything works fine open your browser on **localhost:8080**
But if you have an apache server on your machine or something like that you can simply use the project folder on **/var/www/html**, because it is a static page that only depends on **index.html** and **app.js**

**Comment by guimard** [comment]
Hi,

thanks, I modified it locally to be able to build with webpack (starting a new project using @vue/cli)
